{
 "title": "ElasticSearch Cluster Health Status Overview",
 "tags": [
  "prometheus",
  "elasticsearch"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "production_eu_cluster",
    "query": "label_values(elasticsearch_cluster_health_status,cluster)"
   },
   {
    "name": "production_us_cluster",
    "query": "label_values(elasticsearch_cluster_health_status,cluster)"
   },
   {
    "name": "staging_cluster",
    "query": "label_values(elasticsearch_cluster_health_status, cluster)"
   },
   {
    "name": "vw_staging",
    "query": "label_values(elasticsearch_cluster_health_status,cluster)"
   },
   {
    "name": "vw_production",
    "query": "label_values(elasticsearch_cluster_health_status,cluster)"
   },
   {
    "name": "att_production_va",
    "query": "label_values(elasticsearch_cluster_health_status,cluster)"
   },
   {
    "name": "ctp_aws_production_fra",
    "query": "label_values(elasticsearch_cluster_health_status,cluster)"
   }
  ]
 },
 "panels": [
  { "title": "Production EU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "singlestat",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(max(elasticsearch_cluster_health_status{color=\"green\"} or up * 0)  by (cluster) + max(elasticsearch_cluster_health_status{color=\"yellow\"} * 2 or up * 0) by (cluster) +  max(elasticsearch_cluster_health_status{color=\"red\"} * 3 or up * 0) by (cluster))"
    }
   ]
  },
  {
   "title": "$production_eu_cluster",
   "type": "graph",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 2 },
   "repeat": "production_eu_cluster",
   "targets": [
    {
     "expr": "max(elasticsearch_cluster_health_status{cluster=\"$production_eu_cluster\",color=\"green\"} == 1)",
     "legendFormat": "green"
    },
    {
     "expr": "max(elasticsearch_cluster_health_status{cluster=\"$production_eu_cluster\", color=\"yellow\"} == 1)",
     "legendFormat": "yellow"
    },
    {
     "expr": "max(elasticsearch_cluster_health_status{cluster=\"$production_eu_cluster\", color=\"red\"} == 1)",
     "legendFormat": "red"
    }
   ]
  },
  {
   "title": "$production_eu_cluster",
   "type": "graph",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 2 },
   "targets": [
    {
     "expr": "max(elasticsearch_cluster_health_status{cluster=\"$production_eu_cluster\",color=\"green\"} == 1)",
     "legendFormat": "green"
    },
    {
     "expr": "max(elasticsearch_cluster_health_status{cluster=\"$production_eu_cluster\", color=\"yellow\"} == 1)",
     "legendFormat": "yellow"
    },
    {
     "expr": "max(elasticsearch_cluster_health_status{cluster=\"$production_eu_cluster\", color=\"red\"} == 1)",
     "legendFormat": "red"
    }
   ]
  },
  {
   "title": "$production_eu_cluster",
   "type": "graph",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 2 },
   "targets": [
    {
     "expr": "max(elasticsearch_cluster_health_status{cluster=\"$production_eu_cluster\",color=\"green\"} == 1)",
     "legendFormat": "green"
    },
    {
     "expr": "max(elasticsearch_cluster_health_status{cluster=\"$production_eu_cluster\", color=\"yellow\"} == 1)",
     "legendFormat": "yellow"
    },
    {
     "expr": "max(elasticsearch_cluster_health_status{cluster=\"$production_eu_cluster\", color=\"red\"} == 1)",
     "legendFormat": "red"
    }
   ]
  },
  {
   "title": "$production_eu_cluster",
   "type": "graph",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 2 },
   "targets": [
    {
     "expr": "max(elasticsearch_cluster_health_status{cluster=\"$production_eu_cluster\",color=\"green\"} == 1)",
     "legendFormat": "green"
    },
    {
     "expr": "max(elasticsearch_cluster_health_status{cluster=\"$production_eu_cluster\", color=\"yellow\"} == 1)",
     "legendFormat": "yellow"
    },
    {
     "expr": "max(elasticsearch_cluster_health_status{cluster=\"$production_eu_cluster\", color=\"red\"} == 1)",
     "legendFormat": "red"
    }
   ]
  },
  {
   "title": "$production_eu_cluster",
   "type": "graph",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 2 },
   "targets": [
    {
     "expr": "max(elasticsearch_cluster_health_status{cluster=\"$production_eu_cluster\",color=\"green\"} == 1)",
     "legendFormat": "green"
    },
    {
     "expr": "max(elasticsearch_cluster_health_status{cluster=\"$production_eu_cluster\", color=\"yellow\"} == 1)",
     "legendFormat": "yellow"
    },
    {
     "expr": "max(elasticsearch_cluster_health_status{cluster=\"$production_eu_cluster\", color=\"red\"} == 1)",
     "legendFormat": "red"
    }
   ]
  },
  {
   "title": "$production_eu_cluster",
   "type": "graph",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 2 },
   "targets": [
    {
     "expr": "max(elasticsearch_cluster_health_status{cluster=\"$production_eu_cluster\",color=\"green\"} == 1)",
     "legendFormat": "green"
    },
    {
     "expr": "max(elasticsearch_cluster_health_status{cluster=\"$production_eu_cluster\", color=\"yellow\"} == 1)",
     "legendFormat": "yellow"
    },
    {
     "expr": "max(elasticsearch_cluster_health_status{cluster=\"$production_eu_cluster\", color=\"red\"} == 1)",
     "legendFormat": "red"
    }
   ]
  },
  {
   "title": "$production_eu_cluster",
   "type": "graph",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "max(elasticsearch_cluster_health_status{cluster=\"$production_eu_cluster\",color=\"green\"} == 1)",
     "legendFormat": "green"
    },
    {
     "expr": "max(elasticsearch_cluster_health_status{cluster=\"$production_eu_cluster\", color=\"yellow\"} == 1)",
     "legendFormat": "yellow"
    },
    {
     "expr": "max(elasticsearch_cluster_health_status{cluster=\"$production_eu_cluster\", color=\"red\"} == 1)",
     "legendFormat": "red"
    }
   ]
  },
  {
   "title": "$production_eu_cluster",
   "type": "graph",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 5 },
   "targets": [
    {
     "expr": "max(elasticsearch_cluster_health_status{cluster=\"$production_eu_cluster\",color=\"green\"} == 1)",
     "legendFormat": "green"
    },
    {
     "expr": "max(elasticsearch_cluster_health_status{cluster=\"$production_eu_cluster\", color=\"yellow\"} == 1)",
     "legendFormat": "yellow"
    },
    {
     "expr": "max(elasticsearch_cluster_health_status{cluster=\"$production_eu_cluster\", color=\"red\"} == 1)",
     "legendFormat": "red"
    }
   ]
  },
  {
   "title": "$production_eu_cluster",
   "type": "graph",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 5 },
   "targets": [
    {
     "expr": "max(elasticsearch_cluster_health_status{cluster=\"$production_eu_cluster\",color=\"green\"} == 1)",
     "legendFormat": "green"
    },
    {
     "expr": "max(elasticsearch_cluster_health_status{cluster=\"$production_eu_cluster\", color=\"yellow\"} == 1)",
     "legendFormat": "yellow"
    },
    {
     "expr": "max(elasticsearch_cluster_health_status{cluster=\"$production_eu_cluster\", color=\"red\"} == 1)",
     "legendFormat": "red"
    }
   ]
  },
  {
   "title": "$production_eu_cluster",
   "type": "graph",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 5 },
   "targets": [
    {
     "expr": "max(elasticsearch_cluster_health_status{cluster=\"$production_eu_cluster\",color=\"green\"} == 1)",
     "legendFormat": "green"
    },
    {
     "expr": "max(elasticsearch_cluster_health_status{cluster=\"$production_eu_cluster\", color=\"yellow\"} == 1)",
     "legendFormat": "yellow"
    },
    {
     "expr": "max(elasticsearch_cluster_health_status{cluster=\"$production_eu_cluster\", color=\"red\"} == 1)",
     "legendFormat": "red"
    }
   ]
  },
  {
   "title": "$production_eu_cluster",
   "type": "graph",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 5 },
   "targets": [
    {
     "expr": "max(elasticsearch_cluster_health_status{cluster=\"$production_eu_cluster\",color=\"green\"} == 1)",
     "legendFormat": "green"
    },
    {
     "expr": "max(elasticsearch_cluster_health_status{cluster=\"$production_eu_cluster\", color=\"yellow\"} == 1)",
     "legendFormat": "yellow"
    },
    {
     "expr": "max(elasticsearch_cluster_health_status{cluster=\"$production_eu_cluster\", color=\"red\"} == 1)",
     "legendFormat": "red"
    }
   ]
  },
  {
   "title": "$production_eu_cluster",
   "type": "graph",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 5 },
   "targets": [
    {
     "expr": "max(elasticsearch_cluster_health_status{cluster=\"$production_eu_cluster\",color=\"green\"} == 1)",
     "legendFormat": "green"
    },
    {
     "expr": "max(elasticsearch_cluster_health_status{cluster=\"$production_eu_cluster\", color=\"yellow\"} == 1)",
     "legendFormat": "yellow"
    },
    {
     "expr": "max(elasticsearch_cluster_health_status{cluster=\"$production_eu_cluster\", color=\"red\"} == 1)",
     "legendFormat": "red"
    }
   ]
  },
  { "title": "Production US", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "type": "singlestat",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(max(elasticsearch_cluster_health_status{color=\"green\"} or up * 0)  by (cluster) + max(elasticsearch_cluster_health_status{color=\"yellow\"} * 2 or up * 0) by (cluster) +  max(elasticsearch_cluster_health_status{color=\"red\"} * 3 or up * 0) by (cluster))"
    }
   ]
  },
  {
   "title": "$production_us_cluster",
   "type": "graph",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 10 },
   "repeat": "production_us_cluster",
   "targets": [
    {
     "expr": "max(elasticsearch_cluster_health_status{cluster=\"$production_us_cluster\",color=\"green\"} == 1)",
     "legendFormat": "green"
    },
    {
     "expr": "max(elasticsearch_cluster_health_status{cluster=\"$production_us_cluster\", color=\"yellow\"} == 1)",
     "legendFormat": "yellow"
    },
    {
     "expr": "max(elasticsearch_cluster_health_status{cluster=\"$production_us_cluster\", color=\"red\"} == 1)",
     "legendFormat": "red"
    }
   ]
  },
  {
   "title": "$production_us_cluster",
   "type": "graph",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 10 },
   "targets": [
    {
     "expr": "max(elasticsearch_cluster_health_status{cluster=\"$production_us_cluster\",color=\"green\"} == 1)",
     "legendFormat": "green"
    },
    {
     "expr": "max(elasticsearch_cluster_health_status{cluster=\"$production_us_cluster\", color=\"yellow\"} == 1)",
     "legendFormat": "yellow"
    },
    {
     "expr": "max(elasticsearch_cluster_health_status{cluster=\"$production_us_cluster\", color=\"red\"} == 1)",
     "legendFormat": "red"
    }
   ]
  },
  {
   "title": "$production_us_cluster",
   "type": "graph",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 10 },
   "targets": [
    {
     "expr": "max(elasticsearch_cluster_health_status{cluster=\"$production_us_cluster\",color=\"green\"} == 1)",
     "legendFormat": "green"
    },
    {
     "expr": "max(elasticsearch_cluster_health_status{cluster=\"$production_us_cluster\", color=\"yellow\"} == 1)",
     "legendFormat": "yellow"
    },
    {
     "expr": "max(elasticsearch_cluster_health_status{cluster=\"$production_us_cluster\", color=\"red\"} == 1)",
     "legendFormat": "red"
    }
   ]
  },
  { "title": "VW Production", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "type": "singlestat",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(max(elasticsearch_cluster_health_status{color=\"green\"} or up * 0)  by (cluster) + max(elasticsearch_cluster_health_status{color=\"yellow\"} * 2 or up * 0) by (cluster) +  max(elasticsearch_cluster_health_status{color=\"red\"} * 3 or up * 0) by (cluster))"
    }
   ]
  },
  {
   "title": "$vw_production",
   "type": "graph",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 15 },
   "repeat": "vw_production",
   "targets": [
    {
     "expr": "max(elasticsearch_cluster_health_status{cluster=\"$vw_production\",color=\"green\"} == 1)",
     "legendFormat": "green"
    },
    {
     "expr": "max(elasticsearch_cluster_health_status{cluster=\"$vw_production\", color=\"yellow\"} == 1)",
     "legendFormat": "yellow"
    },
    {
     "expr": "max(elasticsearch_cluster_health_status{cluster=\"$vw_production\", color=\"red\"} == 1)",
     "legendFormat": "red"
    }
   ]
  },
  {
   "title": "$vw_production",
   "type": "graph",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 15 },
   "targets": [
    {
     "expr": "max(elasticsearch_cluster_health_status{cluster=\"$vw_production\",color=\"green\"} == 1)",
     "legendFormat": "green"
    },
    {
     "expr": "max(elasticsearch_cluster_health_status{cluster=\"$vw_production\", color=\"yellow\"} == 1)",
     "legendFormat": "yellow"
    },
    {
     "expr": "max(elasticsearch_cluster_health_status{cluster=\"$vw_production\", color=\"red\"} == 1)",
     "legendFormat": "red"
    }
   ]
  },
  { "title": "AWS Production FRA", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "type": "singlestat",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(max(elasticsearch_cluster_health_status{color=\"green\"} or up * 0)  by (cluster) + max(elasticsearch_cluster_health_status{color=\"yellow\"} * 2 or up * 0) by (cluster) +  max(elasticsearch_cluster_health_status{color=\"red\"} * 3 or up * 0) by (cluster))"
    }
   ]
  },
  {
   "title": "$ctp_aws_production_fra",
   "type": "graph",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 20 },
   "repeat": "ctp_aws_production_fra",
   "targets": [
    {
     "expr": "max(elasticsearch_cluster_health_status{cluster=\"$ctp_aws_production_fra\",color=\"green\"} == 1)",
     "legendFormat": "green"
    },
    {
     "expr": "max(elasticsearch_cluster_health_status{cluster=\"$ctp_aws_production_fra\", color=\"yellow\"} == 1)",
     "legendFormat": "yellow"
    },
    {
     "expr": "max(elasticsearch_cluster_health_status{cluster=\"$ctp_aws_production_fra\", color=\"red\"} == 1)",
     "legendFormat": "red"
    }
   ]
  },
  {
   "title": "$ctp_aws_production_fra",
   "type": "graph",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 20 },
   "targets": [
    {
     "expr": "max(elasticsearch_cluster_health_status{cluster=\"$ctp_aws_production_fra\",color=\"green\"} == 1)",
     "legendFormat": "green"
    },
    {
     "expr": "max(elasticsearch_cluster_health_status{cluster=\"$ctp_aws_production_fra\", color=\"yellow\"} == 1)",
     "legendFormat": "yellow"
    },
    {
     "expr": "max(elasticsearch_cluster_health_status{cluster=\"$ctp_aws_production_fra\", color=\"red\"} == 1)",
     "legendFormat": "red"
    }
   ]
  },
  {
   "title": "$ctp_aws_production_fra",
   "type": "graph",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 20 },
   "targets": [
    {
     "expr": "max(elasticsearch_cluster_health_status{cluster=\"$ctp_aws_production_fra\",color=\"green\"} == 1)",
     "legendFormat": "green"
    },
    {
     "expr": "max(elasticsearch_cluster_health_status{cluster=\"$ctp_aws_production_fra\", color=\"yellow\"} == 1)",
     "legendFormat": "yellow"
    },
    {
     "expr": "max(elasticsearch_cluster_health_status{cluster=\"$ctp_aws_production_fra\", color=\"red\"} == 1)",
     "legendFormat": "red"
    }
   ]
  },
  { "title": "AWS Production ATT", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "type": "singlestat",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(max(elasticsearch_cluster_health_status{color=\"green\"} or up * 0)  by (cluster) + max(elasticsearch_cluster_health_status{color=\"yellow\"} * 2 or up * 0) by (cluster) +  max(elasticsearch_cluster_health_status{color=\"red\"} * 3 or up * 0) by (cluster))"
    }
   ]
  },
  {
   "title": "$att_production_va",
   "type": "graph",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 25 },
   "repeat": "att_production_va",
   "targets": [
    {
     "expr": "max(elasticsearch_cluster_health_status{cluster=\"$att_production_va\",color=\"green\"} == 1)",
     "legendFormat": "green"
    },
    {
     "expr": "max(elasticsearch_cluster_health_status{cluster=\"$att_production_va\", color=\"yellow\"} == 1)",
     "legendFormat": "yellow"
    },
    {
     "expr": "max(elasticsearch_cluster_health_status{cluster=\"$att_production_va\", color=\"red\"} == 1)",
     "legendFormat": "red"
    }
   ]
  },
  {
   "title": "$att_production_va",
   "type": "graph",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "expr": "max(elasticsearch_cluster_health_status{cluster=\"$att_production_va\",color=\"green\"} == 1)",
     "legendFormat": "green"
    },
    {
     "expr": "max(elasticsearch_cluster_health_status{cluster=\"$att_production_va\", color=\"yellow\"} == 1)",
     "legendFormat": "yellow"
    },
    {
     "expr": "max(elasticsearch_cluster_health_status{cluster=\"$att_production_va\", color=\"red\"} == 1)",
     "legendFormat": "red"
    }
   ]
  },
  {
   "title": "Staging",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "type": "singlestat",
     "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "max(max(elasticsearch_cluster_health_status{color=\"green\"} or up * 0)  by (cluster) + max(elasticsearch_cluster_health_status{color=\"yellow\"} * 2 or up * 0) by (cluster) +  max(elasticsearch_cluster_health_status{color=\"red\"} * 3 or up * 0) by (cluster))"
      }
     ]
    },
    {
     "title": "$staging_cluster",
     "type": "graph",
     "gridPos": { "h": 3, "w": 6, "x": 0, "y": 30 },
     "repeat": "staging_cluster",
     "targets": [
      {
       "expr": "max(elasticsearch_cluster_health_status{cluster=\"$staging_cluster\",color=\"green\"} == 1)",
       "legendFormat": "green"
      },
      {
       "expr": "max(elasticsearch_cluster_health_status{cluster=\"$staging_cluster\", color=\"yellow\"} == 1)",
       "legendFormat": "yellow"
      },
      {
       "expr": "max(elasticsearch_cluster_health_status{cluster=\"$staging_cluster\", color=\"red\"} == 1)",
       "legendFormat": "red"
      }
     ]
    },
    {
     "title": "$staging_cluster",
     "type": "graph",
     "gridPos": { "h": 3, "w": 6, "x": 6, "y": 30 },
     "targets": [
      {
       "expr": "max(elasticsearch_cluster_health_status{cluster=\"$staging_cluster\",color=\"green\"} == 1)",
       "legendFormat": "green"
      },
      {
       "expr": "max(elasticsearch_cluster_health_status{cluster=\"$staging_cluster\", color=\"yellow\"} == 1)",
       "legendFormat": "yellow"
      },
      {
       "expr": "max(elasticsearch_cluster_health_status{cluster=\"$staging_cluster\", color=\"red\"} == 1)",
       "legendFormat": "red"
      }
     ]
    },
    {
     "title": "$staging_cluster",
     "type": "graph",
     "gridPos": { "h": 3, "w": 6, "x": 12, "y": 30 },
     "targets": [
      {
       "expr": "max(elasticsearch_cluster_health_status{cluster=\"$staging_cluster\",color=\"green\"} == 1)",
       "legendFormat": "green"
      },
      {
       "expr": "max(elasticsearch_cluster_health_status{cluster=\"$staging_cluster\", color=\"yellow\"} == 1)",
       "legendFormat": "yellow"
      },
      {
       "expr": "max(elasticsearch_cluster_health_status{cluster=\"$staging_cluster\", color=\"red\"} == 1)",
       "legendFormat": "red"
      }
     ]
    },
    {
     "title": "$staging_cluster",
     "type": "graph",
     "gridPos": { "h": 3, "w": 6, "x": 18, "y": 30 },
     "targets": [
      {
       "expr": "max(elasticsearch_cluster_health_status{cluster=\"$staging_cluster\",color=\"green\"} == 1)",
       "legendFormat": "green"
      },
      {
       "expr": "max(elasticsearch_cluster_health_status{cluster=\"$staging_cluster\", color=\"yellow\"} == 1)",
       "legendFormat": "yellow"
      },
      {
       "expr": "max(elasticsearch_cluster_health_status{cluster=\"$staging_cluster\", color=\"red\"} == 1)",
       "legendFormat": "red"
      }
     ]
    },
    {
     "title": "$staging_cluster",
     "type": "graph",
     "gridPos": { "h": 3, "w": 6, "x": 0, "y": 33 },
     "targets": [
      {
       "expr": "max(elasticsearch_cluster_health_status{cluster=\"$staging_cluster\",color=\"green\"} == 1)",
       "legendFormat": "green"
      },
      {
       "expr": "max(elasticsearch_cluster_health_status{cluster=\"$staging_cluster\", color=\"yellow\"} == 1)",
       "legendFormat": "yellow"
      },
      {
       "expr": "max(elasticsearch_cluster_health_status{cluster=\"$staging_cluster\", color=\"red\"} == 1)",
       "legendFormat": "red"
      }
     ]
    }
   ]
  },
  {
   "title": "VW Staging",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "panels": [
    {
     "type": "singlestat",
     "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "max(max(elasticsearch_cluster_health_status{color=\"green\"} or up * 0)  by (cluster) + max(elasticsearch_cluster_health_status{color=\"yellow\"} * 2 or up * 0) by (cluster) +  max(elasticsearch_cluster_health_status{color=\"red\"} * 3 or up * 0) by (cluster))"
      }
     ]
    },
    {
     "title": "$vw_staging",
     "type": "graph",
     "gridPos": { "h": 3, "w": 12, "x": 0, "y": 31 },
     "repeat": "vw_staging",
     "targets": [
      {
       "expr": "max(elasticsearch_cluster_health_status{cluster=\"$vw_staging\",color=\"green\"} == 1)",
       "legendFormat": "green"
      },
      {
       "expr": "max(elasticsearch_cluster_health_status{cluster=\"$vw_staging\", color=\"yellow\"} == 1)",
       "legendFormat": "yellow"
      },
      {
       "expr": "max(elasticsearch_cluster_health_status{cluster=\"$vw_staging\", color=\"red\"} == 1)",
       "legendFormat": "red"
      }
     ]
    },
    {
     "title": "$vw_staging",
     "type": "graph",
     "gridPos": { "h": 3, "w": 12, "x": 12, "y": 31 },
     "targets": [
      {
       "expr": "max(elasticsearch_cluster_health_status{cluster=\"$vw_staging\",color=\"green\"} == 1)",
       "legendFormat": "green"
      },
      {
       "expr": "max(elasticsearch_cluster_health_status{cluster=\"$vw_staging\", color=\"yellow\"} == 1)",
       "legendFormat": "yellow"
      },
      {
       "expr": "max(elasticsearch_cluster_health_status{cluster=\"$vw_staging\", color=\"red\"} == 1)",
       "legendFormat": "red"
      }
     ]
    }
   ]
  }
 ]
}